name: gad_app_team
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1/**

# * 프로젝트 이름: Mindrium version: 1.0.0+1/**
# * 현재 상태: 초기 버전 - Git에 첫 업로드 완료
# * 주요 내용:
# * - 기준 버전: 250625에 업로드된 zip 파일
# * - 현재 main 브랜치 기준으로 작업 진행 중
# *
# * 추가된 기능:
# * 1. 위젯 기능 구현
# *    - 사용자 인터페이스 개선
# *    - 상태 관리 provider 사용
# * 2. 걱정 그룹 기능 추가
# *    - 그룹 생성 및 관리 로직 구현
# *    - Firebase Firestore 연동
# *

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ----------------------------------------------------------------
  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  flutter_secure_storage: ^9.0.0

  # 상태 관리
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9

  # UI / 유틸
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.1.4
  flutter_localizations:
    sdk: flutter

  # 차트 / 캘린더
  fl_chart: ^1.0.0
  table_calendar: ^3.0.9

  # 미디어
  audioplayers: ^6.4.0
  camera: ^0.11.1
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  path_provider: ^2.1.1
  path: ^1.8.3

  # 지도 / 위치 / 지오펜스 / 정적 HTTP
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  http: ^1.4.0

  # 위치 권한 및 현재 위치 얻기
  geolocator: ^14.0.1
  geocoding: ^4.0.0

  # 지오펜스 감지
  geofence_service: ^6.0.0

  # 로컬 푸시 알림
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1

  # 권한 요청
  permission_handler: ^12.0.0+1

  # 기타 기존 패키지
  google_fonts: ^6.2.1

  # home_widget: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/image/logo.png
    - assets/image/activating event.png
    - assets/image/belief.png
    - assets/image/consequence.png
    - assets/image/question_icon.png
    - assets/image/nice.png

    # 1주차 part1
    - assets/education_data/week1_part1_1.json
    - assets/education_data/week1_part1_2.json
    - assets/education_data/week1_part1_3.json
    - assets/education_data/week1_part1_4.json
    - assets/education_data/week1_part1_5.json
    - assets/education_data/week1_part1_6.json

    # 1주차 part2
    - assets/education_data/week1_part2_1.json
    - assets/education_data/week1_part2_2.json
    - assets/education_data/week1_part2_3.json

    # 1주차 part3
    - assets/education_data/week1_part3_1.json
    - assets/education_data/week1_part3_2.json
    - assets/education_data/week1_part3_3.json
    - assets/education_data/week1_part3_4.json
    - assets/education_data/week1_part3_5.json
    - assets/education_data/week1_part3_6.json
    - assets/education_data/week1_part3_7.json
    - assets/education_data/week1_part3_8.json
    - assets/education_data/week1_part3_9.json

    # 1주차 part4
    - assets/education_data/week1_part4_1.json
    - assets/education_data/week1_part4_2.json
    - assets/education_data/week1_part4_3.json
    - assets/education_data/week1_part4_4.json
    - assets/education_data/week1_part4_5.json
    - assets/education_data/week1_part4_6.json

    # 1주차 part5
    - assets/education_data/week1_part5_1.json
    - assets/education_data/week1_part5_2.json
    - assets/education_data/week1_part5_3.json
    - assets/education_data/week1_part5_4.json
    - assets/education_data/week1_part5_5.json
    - assets/education_data/week1_part5_6.json
    - assets/education_data/week1_part5_7.json

    # 1주차 part6
    - assets/education_data/week1_part6_1.json
    - assets/education_data/week1_part6_2.json
    - assets/education_data/week1_part6_3.json
    - assets/education_data/week1_part6_4.json

flutter_native_splash:
  color: "#F9F5F9"
  image: assets/image/logo.png
  android: true
  ios: true
  fullscreen: true