// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL2QK8Yp-4DKpzZPckoUKZVnvGuSJS6og',
    appId: '1:775939862721:web:cf25bd85018b3aee89e440',
    messagingSenderId: '775939862721',
    projectId: 'mindrium-8ff46',
    authDomain: 'mindrium-8ff46.firebaseapp.com',
    storageBucket: 'mindrium-8ff46.firebasestorage.app',
    measurementId: 'G-DKM054T03K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjfVRvNWiQ4NiXsZHLZDYXP636J26U_nw',
    appId: '1:775939862721:android:81d5311845a1f5c989e440',
    messagingSenderId: '775939862721',
    projectId: 'mindrium-8ff46',
    storageBucket: 'mindrium-8ff46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXFTIJxWDybPam6J2SR3ie9jGrWUp5rYA',
    appId: '1:775939862721:ios:42040243cdaecb7d89e440',
    messagingSenderId: '775939862721',
    projectId: 'mindrium-8ff46',
    storageBucket: 'mindrium-8ff46.firebasestorage.app',
    iosBundleId: 'com.mindrium.gadApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXFTIJxWDybPam6J2SR3ie9jGrWUp5rYA',
    appId: '1:775939862721:ios:745094f3af6b98e789e440',
    messagingSenderId: '775939862721',
    projectId: 'mindrium-8ff46',
    storageBucket: 'mindrium-8ff46.firebasestorage.app',
    iosBundleId: 'com.mindrium.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL2QK8Yp-4DKpzZPckoUKZVnvGuSJS6og',
    appId: '1:775939862721:web:61137097a89ffc7589e440',
    messagingSenderId: '775939862721',
    projectId: 'mindrium-8ff46',
    authDomain: 'mindrium-8ff46.firebaseapp.com',
    storageBucket: 'mindrium-8ff46.firebasestorage.app',
    measurementId: 'G-VDWSNBV1L7',
  );
}
